name: chop_url
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.3

dependencies:
  bcrypt: ^1.1.3
  cuid2: ^3.1.0
  dart_jsonwebtoken: ^3.1.1
  darto: ^0.0.22
  dartonic: ^0.0.7
  uuid: ^4.5.1
  zard: ^0.0.13

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
